### ISSUE TITLE
Error `mcopy` invocation failed: `mcopy: No directory slots`

### ISSUE THREAD

**Issue by LeSnake04** [hartwork/grub2-theme-preview#28]
OS: Artix
using pip version

```
 grub2-theme-preview --grub-cfg ./grub.cfg --verbose --debug Downloads/grub/primitivistical-grub-v0.2/Primitivistical/

>>> grub.cfg <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
loadfont $prefix/fonts/unicode.pf2
insmod all_video
insmod gfxterm
insmod png
insmod tga
insmod jpeg

#
# DO NOT EDIT THIS FILE
#
# It is automatically generated by grub-mkconfig using templates
# from /etc/grub.d and settings from /etc/default/grub
#

### BEGIN /etc/grub.d/00_header ###
insmod part_gpt
insmod part_msdos
if [ -s $prefix/grubenv ]; then
  load_env
fi
if [ "${next_entry}" ] ; then
   set default="${next_entry}"
   set next_entry=
   save_env next_entry
   set boot_once=true
else
   set default="Artix Linux, mit Linux linux-zen"
fi

if [ x"${feature_menuentry_id}" = xy ]; then
  menuentry_id_option="--id"
else
  menuentry_id_option=""
fi

export menuentry_id_option

if [ "${prev_saved_entry}" ]; then
  set saved_entry="${prev_saved_entry}"
  save_env saved_entry
  set prev_saved_entry=
  save_env prev_saved_entry
  set boot_once=true
fi

function savedefault {
  if [ -z "${boot_once}" ]; then
    saved_entry="${chosen}"
    save_env saved_entry
  fi
}

function load_video {
  if [ x$feature_all_video_module = xy ]; then
    insmod all_video
  else
    insmod efi_gop
    insmod efi_uga
    insmod ieee1275_fb
    insmod vbe
    insmod vga
    insmod video_bochs
    insmod video_cirrus
  fi
}

set menu_color_normal=light-blue/black
set menu_color_highlight=light-cyan/blue

if [ x$feature_default_font_path = xy ] ; then
   font=unicode
else
insmod part_gpt
insmod btrfs
set root='hd0'  # replaced by grub2-theme-preview, was 'hd2,gpt3'
if [ x$feature_platform_search_hint = xy ]; then
  search --no-floppy --fs-uuid --set=root --hint-bios=hd2,gpt3 --hint-efi=hd2,gpt3 --hint-baremetal=ahci2,gpt3  b80e6511-2de5-41bb-a550-8961913b1ceb
else
  search --no-floppy --fs-uuid --set=root b80e6511-2de5-41bb-a550-8961913b1ceb
fi
    font="/@/usr/share/grub/unicode.pf2"
fi

if loadfont $font ; then
  set gfxmode=1024x768,800x600
  load_video
  insmod gfxterm
  set locale_dir=$prefix/locale
  set lang=de_DE
  insmod gettext
fi
terminal_input console
terminal_output gfxterm
insmod part_gpt
insmod btrfs
set root='hd0'  # replaced by grub2-theme-preview, was 'hd2,gpt3'
if [ x$feature_platform_search_hint = xy ]; then
  search --no-floppy --fs-uuid --set=root --hint-bios=hd2,gpt3 --hint-efi=hd2,gpt3 --hint-baremetal=ahci2,gpt3  b80e6511-2de5-41bb-a550-8961913b1ceb
else
  search --no-floppy --fs-uuid --set=root b80e6511-2de5-41bb-a550-8961913b1ceb
fi
insmod gfxmenu
insmod png
set theme=($root)/@/boot/grub/themes/Primitivistical/theme.txt
export theme
if [ x$feature_timeout_style = xy ] ; then
  set timeout_style=menu
  set timeout=3
# Fallback normal timeout code in case the timeout_style feature is
# unavailable.
else
  set timeout=3
fi
### END /etc/grub.d/00_header ###

### BEGIN /etc/grub.d/01_grub-customizer_menu_color_helper ###
### END /etc/grub.d/01_grub-customizer_menu_color_helper ###

### BEGIN /etc/grub.d/10_linux_proxy ###



if [ "x$default" = 'Artix Linux, mit Linux linux-zen' ]; then default='Advanced options for Artix Linux>Artix Linux, mit Linux linux-zen'; fi;
menuentry "Artix Linux, mit Linux linux-zen" --class artix --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-linux-zen-advanced-b80e6511-2de5-41bb-a550-8961913b1ceb' {
		load_video
		set gfxpayload=keep
		insmod gzio
		insmod part_gpt
		insmod btrfs
		set root='hd0'  # replaced by grub2-theme-preview, was 'hd2,gpt3'
		if [ x$feature_platform_search_hint = xy ]; then
		  search --no-floppy --fs-uuid --set=root --hint-bios=hd2,gpt3 --hint-efi=hd2,gpt3 --hint-baremetal=ahci2,gpt3  b80e6511-2de5-41bb-a550-8961913b1ceb
		else
		  search --no-floppy --fs-uuid --set=root b80e6511-2de5-41bb-a550-8961913b1ceb
		fi
		echo	'Linux linux-zen wird geladen …'
		linux	/@/boot/vmlinuz-linux-zen root=UUID=b80e6511-2de5-41bb-a550-8961913b1ceb rw rootflags=subvol=@ net.ifnames=0 verbose resume=UUID=4296f87c-4437-40e6-b723-f856139bb9e8
		echo	'Initiale Ramdisk wird geladen …'
		initrd	/@/boot/initramfs-linux-zen.img
}
### END /etc/grub.d/10_linux_proxy ###

### BEGIN /etc/grub.d/30_os-prober ###
menuentry 'Windows Boot Manager (auf /dev/sda2)' --class windows --class os $menuentry_id_option 'osprober-efi-3455-753F' {
	insmod part_gpt
	insmod fat
	set root='hd0'  # replaced by grub2-theme-preview, was 'hd0,gpt2'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt2 --hint-efi=hd0,gpt2 --hint-baremetal=ahci0,gpt2  3455-753F
	else
	  search --no-floppy --fs-uuid --set=root 3455-753F
	fi
	chainloader /efi/Microsoft/Boot/bootmgfw.efi
}
### END /etc/grub.d/30_os-prober ###

### BEGIN /etc/grub.d/33_linux_proxy ###
submenu "Erweiterte Optionen für Artix Linux"{
menuentry "Artix Linux" --class artix --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-b80e6511-2de5-41bb-a550-8961913b1ceb' {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_gpt
	insmod btrfs
	set root='hd0'  # replaced by grub2-theme-preview, was 'hd2,gpt3'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd2,gpt3 --hint-efi=hd2,gpt3 --hint-baremetal=ahci2,gpt3  b80e6511-2de5-41bb-a550-8961913b1ceb
	else
	  search --no-floppy --fs-uuid --set=root b80e6511-2de5-41bb-a550-8961913b1ceb
	fi
	echo	'Linux linux-zen wird geladen …'
	linux	/@/boot/vmlinuz-linux-zen root=UUID=b80e6511-2de5-41bb-a550-8961913b1ceb rw rootflags=subvol=@ net.ifnames=0 verbose resume=UUID=4296f87c-4437-40e6-b723-f856139bb9e8
	echo	'Initiale Ramdisk wird geladen …'
	initrd	/@/boot/initramfs-linux-zen.img
}
menuentry "Artix Linux, mit Linux linux" --class artix --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-linux-advanced-b80e6511-2de5-41bb-a550-8961913b1ceb' {
		load_video
		set gfxpayload=keep
		insmod gzio
		insmod part_gpt
		insmod btrfs
		set root='hd0'  # replaced by grub2-theme-preview, was 'hd2,gpt3'
		if [ x$feature_platform_search_hint = xy ]; then
		  search --no-floppy --fs-uuid --set=root --hint-bios=hd2,gpt3 --hint-efi=hd2,gpt3 --hint-baremetal=ahci2,gpt3  b80e6511-2de5-41bb-a550-8961913b1ceb
		else
		  search --no-floppy --fs-uuid --set=root b80e6511-2de5-41bb-a550-8961913b1ceb
		fi
		echo	'Linux linux wird geladen …'
		linux	/@/boot/vmlinuz-linux root=UUID=b80e6511-2de5-41bb-a550-8961913b1ceb rw rootflags=subvol=@ net.ifnames=0 verbose resume=UUID=4296f87c-4437-40e6-b723-f856139bb9e8
		echo	'Initiale Ramdisk wird geladen …'
		initrd	/@/boot/initramfs-linux.img
}
menuentry "Artix Linux, with Linux linux-zen (fallback initramfs)" --class artix --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-linux-zen-fallback-b80e6511-2de5-41bb-a550-8961913b1ceb' {
		load_video
		set gfxpayload=keep
		insmod gzio
		insmod part_gpt
		insmod btrfs
		set root='hd0'  # replaced by grub2-theme-preview, was 'hd2,gpt3'
		if [ x$feature_platform_search_hint = xy ]; then
		  search --no-floppy --fs-uuid --set=root --hint-bios=hd2,gpt3 --hint-efi=hd2,gpt3 --hint-baremetal=ahci2,gpt3  b80e6511-2de5-41bb-a550-8961913b1ceb
		else
		  search --no-floppy --fs-uuid --set=root b80e6511-2de5-41bb-a550-8961913b1ceb
		fi
		echo	'Linux linux-zen wird geladen …'
		linux	/@/boot/vmlinuz-linux-zen root=UUID=b80e6511-2de5-41bb-a550-8961913b1ceb rw rootflags=subvol=@ net.ifnames=0 verbose resume=UUID=4296f87c-4437-40e6-b723-f856139bb9e8
		echo	'Initiale Ramdisk wird geladen …'
		initrd	/@/boot/initramfs-linux-zen-fallback.img
}
menuentry "Artix Linux, with Linux linux (fallback initramfs)" --class artix --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-linux-fallback-b80e6511-2de5-41bb-a550-8961913b1ceb' {
		load_video
		set gfxpayload=keep
		insmod gzio
		insmod part_gpt
		insmod btrfs
		set root='hd0'  # replaced by grub2-theme-preview, was 'hd2,gpt3'
		if [ x$feature_platform_search_hint = xy ]; then
		  search --no-floppy --fs-uuid --set=root --hint-bios=hd2,gpt3 --hint-efi=hd2,gpt3 --hint-baremetal=ahci2,gpt3  b80e6511-2de5-41bb-a550-8961913b1ceb
		else
		  search --no-floppy --fs-uuid --set=root b80e6511-2de5-41bb-a550-8961913b1ceb
		fi
		echo	'Linux linux wird geladen …'
		linux	/@/boot/vmlinuz-linux root=UUID=b80e6511-2de5-41bb-a550-8961913b1ceb rw rootflags=subvol=@ net.ifnames=0 verbose resume=UUID=4296f87c-4437-40e6-b723-f856139bb9e8
		echo	'Initiale Ramdisk wird geladen …'
		initrd	/@/boot/initramfs-linux-fallback.img
}
menuentry "Artix Linux, mit Linux linux-lts" --class artix --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-linux-lts-advanced-b80e6511-2de5-41bb-a550-8961913b1ceb' {
		load_video
		set gfxpayload=keep
		insmod gzio
		insmod part_gpt
		insmod btrfs
		set root='hd0'  # replaced by grub2-theme-preview, was 'hd2,gpt3'
		if [ x$feature_platform_search_hint = xy ]; then
		  search --no-floppy --fs-uuid --set=root --hint-bios=hd2,gpt3 --hint-efi=hd2,gpt3 --hint-baremetal=ahci2,gpt3  b80e6511-2de5-41bb-a550-8961913b1ceb
		else
		  search --no-floppy --fs-uuid --set=root b80e6511-2de5-41bb-a550-8961913b1ceb
		fi
		echo	'Linux linux-lts wird geladen …'
		linux	/@/boot/vmlinuz-linux-lts root=UUID=b80e6511-2de5-41bb-a550-8961913b1ceb rw rootflags=subvol=@ net.ifnames=0 verbose resume=UUID=4296f87c-4437-40e6-b723-f856139bb9e8
		echo	'Initiale Ramdisk wird geladen …'
		initrd	/@/boot/initramfs-linux-lts.img
}
menuentry "Artix Linux, with Linux linux-lts (fallback initramfs)" --class artix --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-linux-lts-fallback-b80e6511-2de5-41bb-a550-8961913b1ceb' {
		load_video
		set gfxpayload=keep
		insmod gzio
		insmod part_gpt
		insmod btrfs
		set root='hd0'  # replaced by grub2-theme-preview, was 'hd2,gpt3'
		if [ x$feature_platform_search_hint = xy ]; then
		  search --no-floppy --fs-uuid --set=root --hint-bios=hd2,gpt3 --hint-efi=hd2,gpt3 --hint-baremetal=ahci2,gpt3  b80e6511-2de5-41bb-a550-8961913b1ceb
		else
		  search --no-floppy --fs-uuid --set=root b80e6511-2de5-41bb-a550-8961913b1ceb
		fi
		echo	'Linux linux-lts wird geladen …'
		linux	/@/boot/vmlinuz-linux-lts root=UUID=b80e6511-2de5-41bb-a550-8961913b1ceb rw rootflags=subvol=@ net.ifnames=0 verbose resume=UUID=4296f87c-4437-40e6-b723-f856139bb9e8
		echo	'Initiale Ramdisk wird geladen …'
		initrd	/@/boot/initramfs-linux-lts-fallback.img
}
}
### END /etc/grub.d/33_linux_proxy ###

### BEGIN /etc/grub.d/34_linux_xen ###
### END /etc/grub.d/34_linux_xen ###

### BEGIN /etc/grub.d/35_uefi-firmware ###
menuentry 'UEFI Firmware Settings' $menuentry_id_option 'uefi-firmware' {
	fwsetup
}
### END /etc/grub.d/35_uefi-firmware ###

### BEGIN /etc/grub.d/40_custom ###
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
### END /etc/grub.d/40_custom ###

### BEGIN /etc/grub.d/41_custom ###
if [ -f  ${config_directory}/custom.cfg ]; then
  source ${config_directory}/custom.cfg
elif [ -z "${config_directory}" -a -f  $prefix/custom.cfg ]; then
  source $prefix/custom.cfg
fi
### END /etc/grub.d/41_custom ###

### BEGIN /etc/grub.d/42_snapshots-btrfs ###
submenu 'Artix Linux snapshots' {
    configfile "${prefix}/grub-btrfs.cfg"
}
### END /etc/grub.d/42_snapshots-btrfs ###

### BEGIN /etc/grub.d/60_memtest86+ ###
if [ "${grub_platform}" == "pc" ]; then
    menuentry "Memory Tester (memtest86+)" --class memtest86 --class gnu --class tool {
        search --fs-uuid --no-floppy --set=root --hint-bios=hd2,gpt3 --hint-efi=hd2,gpt3 --hint-baremetal=ahci2,gpt3  b80e6511-2de5-41bb-a550-8961913b1ceb
        linux16 /@/boot/memtest86+/memtest.bin 
    }
fi
### END /etc/grub.d/60_memtest86+ ###

submenu 'Reboot / Shutdown' {
    menuentry Reboot { reboot }
    menuentry Shutdown { halt }
}

set default=0
set timeout=30
terminal_output gfxterm
set theme=$prefix/themes/DEMO/theme.txt
>>> grub.cfg <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

INFO: Found OVMF image at '/usr/share/edk2-ovmf/x64/OVMF_CODE.fd'.
# grub-mkrescue --directory=/usr/lib/grub/x86_64-efi --xorriso xorriso --output /tmp/tmpu77ye3cn/grub2_theme_demo.img boot/grub/grub.cfg=/tmp/tmpu77ye3cn/grub.cfg boot/grub/themes/DEMO/=/home/<user>/Downloads/grub/primitivistical-grub-v0.2/Primitivistical
mcopy: No directory slots
grub-mkrescue: Fehler: `mcopy` invocation failed
.
Traceback (most recent call last):
  File "/home/<user>/.local/lib/python3.9/site-packages/grub2_theme_preview/__main__.py", line 464, in main
    _inner_main(options)
  File "/home/<user>/.local/lib/python3.9/site-packages/grub2_theme_preview/__main__.py", line 432, in _inner_main
    raise OSError(errno.ENOENT, '%s failed to create the rescue image' % command)
FileNotFoundError: [Errno 2] grub-mkrescue failed to create the rescue image
ERROR: [Errno 2] grub-mkrescue failed to create the rescue image
```

**Comment by hartwork** [comment]
Hi @LeSnake04, if https://bbs.archlinux.org/viewtopic.php?pid=1983604#p1983604 is correct this is a problem with mtools version 4.0.33 in Arch-based Linux distros. They suggest downgrading mtools to 4.0.31 to make grub-mkrescue work again. Is that something you could try? I'm on Gentoo here and mtools 4.0.33 does not show this issue here.

**Comment by LeSnake04** [comment]
downgrading mtools 4.0.32 fixed it

**Comment by hartwork** [comment]
@LeSnake04 cool, thanks for the update
